### PR TITLE
gemspec enhancement + yard support

### PR DESCRIPTION
**Pull request by noraj**
- add metadata
- add yard documentation support (dev dependency + building command)

### CODE REVIEW

**Comment by alexdalitz** [comment]
Yo dude - thanks for all your PRs!
I'm (sadly) afraid I don't know enough about YARD to deal with this one - could you please leave some comments?
Thanks!

**Comment by noraj** [comment]
Yard is an enhancement of rdoc, the documentation you can see at rubydoc.info is generated with yard.

So https://www.rubydoc.info/gems/dnsruby/ is built with default yard option from the source of your project.
If you want to serve the doc with yard options like adding extra pages you need to host it yourself somewhere else like I did for https://gitlab.com/noraj/nvd_api with the doc hosted on gitlab pages https://gitlab.com/noraj/nvd_api thans to Gitlab CI. It's possible to dothe same with GitHub pages and GitHub actions now.

Anyway YARD is mostly a superset of rdoc and is the new standard nowadays. So if you see nothing wrong at https://www.rubydoc.info/gems/dnsruby/ moving from rdoc to yard will be transparent.

**Comment by noraj** [comment]
And you can also include markdown or rdoc pages in YARD extra pages.

**Comment by noraj** [comment]
@alexdalitz see https://stackoverflow.com/questions/3699706/yard-is-not-the-same-as-rdoc

**Comment by alexdalitz** [comment]
Ok - thanks!
I guess I'll give it a go ;)
Thanks again for all your PRs and help!

**Pull request merged**
