### PR TITLE
Upgrade demos

### PR DESCRIPTION
**Pull request by keithrbennett**
Cleaned up the demo scripts.

### CODE REVIEW

**Comment by keithrbennett** [comment]
Accidentally deleted this branch, which I guess resulted in an automatic closing of the pull request.  I've now recreated the branch.

**Comment by alexdalitz** [comment]
Hi Keith - 

Just noticed that this pull request has been re-opened. Sorry about the delay!

I'll try to look at it this evening; otherwise it will be early next week.

Thanks!


Alex.

**Comment by keithrbennett** [comment]
Alex -

Long time no talk.  I’ve been enjoying a BBC TV show on Netflix — Death in Paradise.  Do you know/watch it?

No problem about the demo code.

- Keith

**Comment by alexdalitz** [comment]
> Long time no talk. I’ve been enjoying a BBC TV show on Netflix — Death in Paradise. Do you know/watch it?

No, never heard of it.

We tend not to watch much TV - other than the occasional nature documentary…

> No problem about the demo code.

I really will try to look at this soon!

I have one more week left on my current contract, and am then not planning to take any more contract work until September/October - meaning I should have much more time left for stuff like dnsruby.

Thanks,


Alex.

> 
> - Keith
> 
> > On May 7, 2015, at 2:41 AM, Alex Dalitz <notifications@github.com> wrote:
> > 
> > Hi Keith -
> > 
> > Just noticed that this pull request has been re-opened. Sorry about the delay!
> > 
> > I'll try to look at it this evening; otherwise it will be early next week.
> > 
> > Thanks!
> > 
> > Alex.
> > 
> > —
> > Reply to this email directly or view it on GitHub <https://github.com/alexdalitz/dnsruby/pull/81#issuecomment-99741672>.
> > 
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/alexdalitz/dnsruby/pull/81#issuecomment-100237814>.
> 


Alex Dalitz
alex@caerkettontech.com

**Pull request merged**
