### PR TITLE
minor edits to comments/sample code

### PR DESCRIPTION
**Pull request by mcr**
some minor adjustments to some comments about sample code based upon experience.

### CODE REVIEW

**Comment by alexdalitz** [comment]
Hi - 

Thanks for the input!

I can see that the changes to the comments should be merged, but I'm unsure about the reasons for moving the method declaration?

Thanks!


Alex.

**Comment by mcr** [comment]
Alex Dalitz <notifications@github.com> wrote:
    > I can see that the changes to the comments should be merged, but I'm
    > unsure about the reasons for moving the method declaration?

It's really the comment that I think should move to above the method
it describes.

**Comment by alexdalitz** [comment]
So, the comment describes the query() method. The method above it is :nodoc:

I'm happy to accept the other changes though.

Thanks!


Alex.

**Comment by alexdalitz** [comment]
Hi - 

As above, I'd be very happy to accept all these changes, other than those to recursor.rb. If it was possible, please, to re-submit this patch with those changes dropped, then I would be happy to accept it.

Thanks!


Alex.

**Comment by alexdalitz** [comment]
Hi - 

I'm sorry, I'd completely forgotten about this pull request. Is it currently in a good place for assessment and merging?

Thanks,

Alex.

**Comment by alexdalitz** [comment]
I'm going to assume that this PR has been abandoned, as I have been unable go get a response from the author.

**Pull request closed without merging**
