### PR TITLE
README: add CAA to list of records supported by this library

### PR DESCRIPTION
**Pull request by parkr**
Supported since v0.60.1: https://github.com/alexdalitz/dnsruby/blob/master/RELEASE_NOTES.md#v1601

/cc @alexdalitz

### CODE REVIEW

**Comment by alexdalitz** [comment]
Sure- sorry about failure :(

I will attend to this when reunited with laptop in a couple of weeks...

Thanks!

**Comment by parkr** [comment]
I'm afraid this may not be possible to fix on your own. It looks like a broken version of bundler on ruby-head. A restart may do the trick.

```text
bundle exec rake test
bundler: failed to load command: rake (/home/travis/build/alexdalitz/dnsruby/vendor/bundle/ruby/2.6.0/bin/rake)
LoadError: cannot load such file -- bundler/dep_proxy
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:888:in `block (2 levels) in expand_dependencies'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `each'
  /home/travis/.rvm/rubies/ruby-head/lib/ruby/gems/2.6.0/gems/bundler-1.16.1/lib/bundler/definition.rb:887:in `block in expand_dependencies'
...
```

**Comment by alexdalitz** [comment]
Happily, this build issue is now fixed for Ruby 2.5.1 and up :-)

Thanks,

Alex.

**Pull request merged**
