### PR TITLE
Work/tcp pipelining

### PR DESCRIPTION
**Pull request by nwitkowski**
Hi Alex,

I work with Keith at Verisign.
Here are some changes relating to tcp pipelining with some unit tests.
The idea is to reuse the same connection to send queries if at all possible.
The unit test use rubydns as a server to test tcp persistent connections.
Let me know if you have any questions/comments/suggestions!

Regards,

Nick

### CODE REVIEW

**Comment by alexdalitz** [comment]
Hi - 

Thanks very much for this contribution to dnsruby!

I'm impressed that you stuck with it through the darkness of the select_thread.rb - not pretty stuff! Which is my main concern about this patch, really - the fact that it goes deep into the dark internals of the IO, which hasn't been touched in several years.

Having said that, I've seen nothing which looks like it should cause any problems, and I'm pleased to see that the pipelining code is mainly orthogonal to the rest of the code (although there are a few places where other code has been changed, this largely seems reasonable).

I notice that the test code all tests pipelining (which is fair enough). But I do worry that not enough testing may have been done on the NON-pipelining stuff - i.e. stress testing "normal" IO paths. Have you run the tc_soak.rb test? Have you done any other stress testing of the normal IO?

[As an aside, I don't think there's any need to add a 2007 Nominet copyright notice on a newly created file!]

Thanks again for your work with this,


Alex.

**Comment by nwitkowski** [comment]
Hi Alex,
I actually spend the day trying to get the tc_soak.rb test to run. It's
very cpu/memory intensive! I couldn't get it to pass in the master or the
work/tcp_pipelining branch. I'm actually thinking about using rubydns as
the local server and always responding the same answer. Do you have any
thoughts?
I'll keep you posted on my progress.
Thanks,
Nick

**Comment by alexdalitz** [comment]
Hi Nick -

Thanks very much for putting in so much effort, and I'm sorry that you wasted a whole day with this. Truth be told, it is a long time since I ran the tc_soak.rb test, and I couldn't say that I know it to work on any particular version of Dnsruby.

Basically, it would be nice just to make sure that it is possible to have many concurrent outstanding (non-pipeline) queries without any issue - which is what tc_soak is supposed to do. I've tried to run it, but it no longer runs in the new test environment :-(   I've emailed Keith to see if he can help me to get the test running again.

Thanks!


Alex.

**Comment by keithrbennett** [comment]
Alex -

I've been working on this for much of yesterday afternoon and today.  After making the changes in my pull request (https://github.com/alexdalitz/dnsruby/pull/75), I no longer get this error:

```
/Users/kbennett/work/dnsruby/test/tc_soak.rb:22:in `require': cannot load such file -- tc_single_resolver (LoadError)
```

However, although I no longer get the above error, I have other errors:

```
➜  dnsruby git:(make-able-to-run-tc-soak-by-itself) ✗ clear; rake test TEST=test/tc_soak.rb
Run options: --seed 49124

# Running:

E.FEE.E.."Query count : 252, 0 timed out. 2.049014 time taken"
.EEE/Users/kbennett/.rvm/gems/ruby-2.1.4/gems/minitest-5.4.2/lib/minitest/parallel.rb:25:in `join': Dnsruby::ServFail (Dnsruby::ServFail)
	from /Users/kbennett/.rvm/gems/ruby-2.1.4/gems/minitest-5.4.2/lib/minitest/parallel.rb:25:in `each'
...
```

After reducing the number of threads from 250 to 50, I get a different error:

```
EEEE..EE.EEdeadlock; recursive locking
/Users/kbennett/work/dnsruby/lib/dnsruby/config.rb:97:in `synchronize'
/Users/kbennett/work/dnsruby/lib/dnsruby/config.rb:97:in `parse_config'
/Users/kbennett/work/dnsruby/lib/dnsruby/config.rb:349:in `to_s'
/Users/kbennett/work/dnsruby/lib/dnsruby/config.rb:344:in `inspect'
```

And when I reduce the number of threads to 5, I see these errors:

```
"Query count : 40000, 3 timed out. 143.292786 time taken"
."Query count : 252, 0 timed out. 2.87408 time taken"
."Query count : 252, 0 timed out. 2.925357 time taken"
.E.F.E.EE.E

Finished in 194.528862s, 0.0668 runs/s, 411.2706 assertions/s.

  1) Error:
TestSingleResolverSoak#test_many_threads_on_one_single_resolver_synchronous:
Dnsruby::ServFail: Dnsruby::ServFail
    /Users/kbennett/work/dnsruby/test/tc_soak.rb:124:in `join'
    /Users/kbennett/work/dnsruby/test/tc_soak.rb:124:in `block in test_many_threads_on_one_single_resolver_synchronous' (thread = #<Thread:0x007f938c35...)
    /Users/kbennett/work/dnsruby/test/tc_soak.rb:123:in `each'
    /Users/kbennett/work/dnsruby/test/tc_soak.rb:123:in `test_many_threads_on_one_single_resolver_synchronous' (threads = [#<Thread:0x007f938c3..., res = #<Dnsruby::SingleReso..., ids = [], mutex = #<Mutex:0x007f938c353..., timed_out = 0, query_count = 5, start = 2015-03-05 13:52:04 -..., num_times = 5, stop = nil, time_taken = nil)


  2) Failure:
TestSingleResolver#test_res_config [/Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:189]:
nameserver() looks up IP..
Expected: "10.0.1.128"
  Actual: ""


  3) Error:
TestSingleResolver#test_options_preserved_on_tcp_resend:
IOError: dnsruby can't connect to 127.0.0.1:59821 from 0.0.0.0:53410, use_tcp=true, exception = Errno::ECONNREFUSED, Connection refused - connect(2) for "127.0.0.1" port 59821
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:288:in `join'
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:288:in `test_options_preserved_on_tcp_resend' (udpPacket = #<Dnsruby::Message:0x..., tcpPacket = nil, port = 59821, thread = #<Thread:0x007f9391d3..., ret = nil, thread2 = #<Thread:0x007f9391d3...)


  4) Error:
TestSingleResolver#test_queries:
Dnsruby::ServFail: Dnsruby::ServFail
    /Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:248:in `send_message' (message = #<Dnsruby::Message:0x..., q = #<Thread::Queue:0x007..., _id = 2015-03-05 16:20:20 -..., result = #<Dnsruby::Message:0x..., error = #<Dnsruby::ServFail: ...)
    /Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:195:in `query' (name = "a.t.dnsruby.validati..., type = A, klass = IN, set_cd = true, msg = #<Dnsruby::Message:0x...)
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:134:in `block (2 levels) in test_queries'
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:132:in `times'
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:132:in `block in test_queries' (data = {:type=>A, :name=>"a...., packet = nil, question = nil, answer = nil)
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:130:in `each'
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:130:in `test_queries' (res = #<Dnsruby::SingleReso...)


  5) Error:
TestSingleResolver#test_truncated_response:
Dnsruby::ServFail: Dnsruby::ServFail
    /Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:248:in `send_message' (message = #<Dnsruby::Message:0x..., q = #<Thread::Queue:0x007..., _id = 2015-03-05 15:10:59 -..., result = #<Dnsruby::Message:0x..., error = #<Dnsruby::ServFail: ...)
    /Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:195:in `query' (name = "overflow.dnsruby.val..., type = "txt", klass = IN, set_cd = true, msg = #<Dnsruby::Message:0x...)
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:201:in `test_truncated_response' (res = #<Dnsruby::SingleReso..., m = nil)


  6) Error:
TestSingleResolver#test_simple:
Dnsruby::ServFail: Dnsruby::ServFail
    /Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:248:in `send_message' (message = #<Dnsruby::Message:0x..., q = #<Thread::Queue:0x007..., _id = 2015-03-05 14:57:51 -..., result = #<Dnsruby::Message:0x..., error = #<Dnsruby::ServFail: ...)
    /Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:195:in `query' (name = "a.t.dnsruby.validati..., type = A, klass = IN, set_cd = true, msg = #<Dnsruby::Message:0x...)
    /Users/kbennett/work/dnsruby/test/tc_single_resolver.rb:54:in `test_simple' (res = #<Dnsruby::SingleReso..., m = nil)

13 runs, 80004 assertions, 1 failures, 5 errors, 0 skips
```

The question is, which of the failures, if any, is really the fault of any Dnsruby code?

A ServFail would not be, right?  But the deadlock may be an error in our code.  Output from another run, without pretty_backtrace, is at https://gist.githubusercontent.com/keithrbennett/367055f26d61ba57d031/raw/b73beabfb3088e0832826c3cbe6e481d5d40f778/gistfile1.txt.

It says there's an "exception : can't add a new key into hash during iteration".  I've seen this when iterating over the keys and values of a hash with each, and trying to modify the hash's keys inside that loop:

```
2.1.4 :001 > h = { a: 1, b: 2, c: 3 }
 => {:a=>1, :b=>2, :c=>3}
2.1.4 :002 > h.each { |key, value| h['some-arbitrary-key'] = 42 }
RuntimeError: can't add a new key into hash during iteration
	from (irb):2:in `block in irb_binding'
	from (irb):2:in `each'
	from (irb):2
	from /Users/kbennett/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'
```

I looked through the code and couldn't find where that was happening.  There are several cases in the code where we have arrays and hashes in '@@' variables.  Can you think of any that might be responsible for this?

By the way, I've removed the use of pretty_backtrace in that pull request.  I'm now sorry I introduced it to the gem.  It was making the output too verbose and it was difficult to read.  It's simple enough to add it in temporarily without committing it if we want it.

**Comment by alexdalitz** [comment]
Hi Nick - 

Thanks for your help on this.

I've pushed some changes to the git repository which should hopefully help with the test.

I absolutely agree that we should use a localhost mock resolver for this!

I'm pushed for time just now, but might be able to knock something up over the weekend. If you already had something you could easily adapt for this, then perhaps we could just use that in the tc_soak test? I presume that the pipelining test server would be easily adapted?

I have no particulary worries about the tc_soak test being run either, really - I just want to make sure that something is run that will test that we can still perform lots of concurrent I/O. Given that the tc_soak code is failing anyway, I don't see that there is any more value in that than any other code which runs many concurrent queries.

Of course, querying remote servers does introduce timing issues (latency) which querying local servers removes - which adds to the load on the software under test.

Thanks!


Alex.

**Comment by keithrbennett** [comment]
A very big part of my troubles running tc_soak seemed to stem from the use of invalid Nominet addresses included from tc_soak_base.  I made changes to tc_soak, and all but 1 of the test methods seemed to perform correctly (though I removed an assert of 'IN' which may be necessary).

You can see my suggested changes on my feature branch at https://github.com/keithrbennett/dnsruby/tree/cleanup_tc_soak.

I eliminated the need for mutexes by having the thread keep and return threadlocal counts, which the main thread gets  by calling Thread#value.

----

There is one test that is problematic.  It may be revealing a failure in thread safety of the library. In the test 'test_many_threads_on_many_single_resolvers' in tc_soak, we get Hash concurrency errors.

I monkey patched the Hash class so that whenever there was an error raised assigning a value it would print out 'caller' (the stack trace).  I put this in spec_helper.rb:

```ruby
class Hash
  alias_method :old_assign, :[]=
  def []=(key, value)
    begin
      old_assign(key, value)
    rescue => e
      puts "Error assigning #{value} to key #{key}"
      puts caller
      raise
    end
  end
end
```

When I ran the test I got this:

```
Error assigning 2015-03-05 19:05:30 -0500 to key [#<Dnsruby::PacketSender:0x007f8c66829390 @ipv6=false, @packet_timeout=4, @port=53, @udp_size=4096, @dnssec=true, @use_tcp=false, @no_tcp=false, @tsig=nil, @ignore_truncation=false, @src_address="0.0.0.0", @src_address6="::", @src_port=[0], @recurse=true, @server="10.170.12.57">, #<Dnsruby::Message:0x007f8c64727930 @header=#<Dnsruby::Header:0x007f8c647278e0 @id=44148, @qr=false, @opcode=Query, @aa=false, @ad=false, @tc=false, @rd=true, @ra=false, @cd=true, @rcode=NOERROR, @qdcount=1, @nscount=0, @ancount=0, @arcount=1>, @question=[#<Dnsruby::Question:0x007f8c64726eb8 @qtype=CNAME, @qclass=IN, @qname=#<Dnsruby::Name: cname.t.dnsruby.validation-test-servers.nominet.org.uk.>>], @answer=[], @authority=[], @additional=[#<Dnsruby::RR::OPT:0x007f8c61564b78 @type=OPT, @ttl=32768, @options=nil, @klass=CLASS4096>], @tsigstate=:Unsigned, @signing=false, @tsigkey=nil, @answerfrom=nil, @answerip=nil, @send_raw=false, @do_validation=true, @do_caching=true, @security_level=UNCHECKED, @security_error=nil, @cached=false>, [127, 15], 0]
/Users/kbennett/work/dnsruby/test/spec_helper.rb:31:in `[]='
/Users/kbennett/work/dnsruby/lib/dnsruby/select_thread.rb:122:in `block in add_to_select'
/Users/kbennett/work/dnsruby/lib/dnsruby/select_thread.rb:116:in `synchronize'
/Users/kbennett/work/dnsruby/lib/dnsruby/select_thread.rb:116:in `add_to_select'
/Users/kbennett/work/dnsruby/lib/dnsruby/packet_sender.rb:427:in `send_dnsruby'
/Users/kbennett/work/dnsruby/lib/dnsruby/packet_sender.rb:346:in `send_async'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:983:in `block (3 levels) in tick'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:969:in `each'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:969:in `block (2 levels) in tick'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:959:in `each'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:959:in `block in tick'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:957:in `synchronize'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:957:in `tick'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:892:in `send_async'
/Users/kbennett/work/dnsruby/lib/dnsruby/resolver.rb:391:in `send_async'
/Users/kbennett/work/dnsruby/test/tc_soak.rb:168:in `block (4 levels) in test_many_threads_on_many_single_resolvers'
/Users/kbennett/work/dnsruby/test/tc_soak.rb:163:in `each'
/Users/kbennett/work/dnsruby/test/tc_soak.rb:163:in `block (3 levels) in test_many_threads_on_many_single_resolvers'
/Users/kbennett/work/dnsruby/test/tc_soak.rb:162:in `times'
/Users/kbennett/work/dnsruby/test/tc_soak.rb:162:in `block (2 levels) in test_many_threads_on_many_single_resolvers'
```

**Comment by alexdalitz** [comment]
Hi -

Could you please try running again, but with line 330 of select_thread.rb changed to :

        timeouts = @@timeouts.clone

(i.e. cloning the timeouts)?

Thanks!


Alex.

**Comment by keithrbennett** [comment]
My apologies.  I thought I was adding comments to the commit, but was adding them to this pull request instead.  Also, Nick, feel free to ignore the cycle suggestion -- it had nothing to do with your changes.

**Comment by nwitkowski** [comment]
Hi,

Regarding:
```
    timeouts = @@timeouts.clone
```
It’s because @@timeouts is protected by a mutex. If you don’t clone the object then you can have concurrent access to the @@timeouts variable since timeouts and @@timeouts will point to the same memory location. This illustrates my point using irb:
```
irb(main):001:0> timeouts = [1,2,3]
=> [1, 2, 3]
irb(main):002:0> t = timeouts
=> [1, 2, 3]
irb(main):003:0> timeouts << 4
=> [1, 2, 3, 4]
irb(main):004:0> print t
[1, 2, 3, 4]=> nil
irb(main):005:0> 
```
Here timeouts and t are essentially the same variable. There's no point in protecting one with a mutex if you have the other one still used later on in the code. That's why I use the clone method since it copies the object and later accesses to the variable will be independent to @@timeouts.

Nick

**Comment by keithrbennett** [comment]
As a data point, I just reinstalled Ruby 1.9.3 (with rvm), ran bundle, and then ran rake soak.

The tests were all successful.  I don't understand why it failed for Travis CI but it may not represent a failure of the software.

**Comment by nwitkowski** [comment]
I think Travis only runs rake test. 
From the log it looks like a connection refused in tc_tcp, could be the environment.
They seem to be running fine on my branch though:
https://travis-ci.org/nwitkowski/dnsruby

**Comment by keithrbennett** [comment]
Doh!  Yes, Nick, you're right.  rake test, not rake anything else.

I confirmed on my side rake test works fine too.

Alex, it seems like we've had this kind of problem with Travis several times, no?  I wonder if there's something flaky about their environment.

I just checked, and yes, there have been problems reported, but mainly in 2013.  Travis has a blog post at http://blog.travis-ci.com/2013-05-20-network-timeouts-build-retries/.  I posted a message explaining our situation and asking about it.  Strange thing is that although it's a network error, the host that's refusing the connection is localhost!

**Comment by alexdalitz** [comment]
So I think I might not have been clear.

I was wondering, given that I am having problems running the soak test, if somebody else would be kind enough to run it with the original lib source, but with the @@timeouts.clone line I suggested above?

From your reponse, it sounds like that line has also been changed in your patch. That's great.

I was keen to try to get the test to pass with the original source, and then pass with the patch - just for peace of mind, really.

Thanks!


Alex.

**Comment by nwitkowski** [comment]
Not sure if that's what you want but I created a branch off of master and added my changes to run tc_soak:
https://github.com/nwitkowski/dnsruby/commit/167aefb48ddb5fa2863d220633302ff862cf0a44
It passes the rake soak tests without a glitch.
Here's the modifications I did:
* Disable validation, validation causes a lot of re-queries to other dns servers
* Disable caching, just to be safe
* Allow the SingleResolver to use a port along with server parameter
* Have the tests run specifically in udp or tcp mode
* Added the @@timeouts.clone line

Nick

**Comment by alexdalitz** [comment]
Magic - thanks a million!

**Comment by alexdalitz** [comment]
However, I'm afraid that we need to resolve some conflicts before I can accept the merge. Sorry about that...

If you could please be so kind as to resolve said conflicts, I'd be happy to merge once we can bully Travis into submission.

Thanks!


Alex.

**Comment by nwitkowski** [comment]
OK the said conflicts are resolved, Travis CI passed :-)
We're good to go!

Nick

**Comment by alexdalitz** [comment]
Great - thanks!

**Pull request merged**
