### PR TITLE
Add string import to zone reader

### PR DESCRIPTION
**Pull request by tg90nor**

### CODE REVIEW

**Comment by alexdalitz** [comment]
Hi - 

Is this still an issue?

Thanks,

Alex.

**Comment by keithrbennett** [comment]
I'm ok with the status quo but see the value in making it more obvious that a string can be used here.  @tg90nor, if you are willing, it would be helpful to:

1) test the StringIo approach I mentioned
2) put a short comment in the process_file method documentation saying something like:
"Outputting to strings can be accomplished by using a StringIo object instead of a file."

We might want to even create a method alias for process_file named 'process_io' to make it clear to anyone getting a list of instance methods that any IO object will work:

```ruby
alias_method :process_io, :process_file
```

**Comment by tg90nor** [comment]
I have not had much time to work on this, but I like the suggestion of using StringIO.

Since the process_file method expects a filename as its argument, it might be better to create a new process_io method, for simplicity. Then maybe have the process_file method call process_io to avoid code duplication.

I will try to find some time to test this approach in a few days.

**Comment by tg90nor** [comment]
Added a process_io method, made process_file use process_io, and added some simple tests for the zone reader.

**Comment by keithrbennett** [comment]
Thomas -

The Minitest file at https://gist.github.com/keithrbennett/8dc26274d5203bf5b45a illustrates that IO.foreach(filespec) will open and close the file, but I believe the approach you used would leave an open file hanging around even after completing its use.

Because of this, I think it's best to continue to use IO.foreach, and, as before, have the method take as its parameter the thing that will be passed to IO.foreach, that is, an IO object or a filespec string.

Also, in the parse exception message, inspect can be called on the IO or string parameter to show information about it, so there's no need for the extra filename parameter:

```ruby
2.1.5 :025 > puts File.open('/Users/kbennett/.zshrc').inspect
#<File:/Users/kbennett/.zshrc>

2.1.5 :026 > puts 'my_filespec'.inspect
"my_filespec"

2.1.5 :027 > puts StringIO.new.inspect
#<StringIO:0x007fd0da872230>
```

Because of these things, the distinction between the two method signatures can go away, and they can be a single method available with the two names.  Using alias_method makes explicit to the reader that these are identical methods and has the benefit of not adding any method implementation code.

**Comment by tg90nor** [comment]
I believe merging process_file and process_io would either break backwards compatibility or require logic to determine whether a filename or a IO object was passed to the method.

I will modify the code to use the inspect method to show object type and filename.

Also, the documentation is not clear on whether IO.foreach accepts IO objects, or just filenames. If it accepts IO objects, then the original code can be used with StringIO objects, and none of my changes are needed.

**Comment by tg90nor** [comment]
IO.foreach does not seem to work with StringIO objects.

I am undecided on whether I should close the IO object in process_io, or leave that to the caller of the method. Any thoughts?

**Comment by keithrbennett** [comment]
Wow, that's an unfortunate surprise (that IO.foreach doesn't work with StringIO).

You could always test to see if the object is a StringIO, and, if so, use its each_line instead of IO's foreach.

I think the general pattern to follow is only close things that you open -- so if you're passed a file name and open a file with it, that file should be closed when done; which is what IO.foreach seems to do.  But if someone passes an open file, I would leave it to them to close it themselves.  That's a little less handy for the caller, but I think it's better to leave open the possibility that they might want to continue to use the handle for something else (rewind it, or maybe it's a socket, etc.).

**Comment by keithrbennett** [comment]
If you do add support for StringIO's, I suggest organizing the code to minimize duplication.  The code inside the existing foreach could be extracted out into a method; a lambda would be a little easier because it would have access to the local variables (zone and line_num), so less passing would need to be done.  I could provide more detail about that if you like.

**Comment by tg90nor** [comment]
Since I made process_file use process_io, there is no code duplication.
I have now made process_file close the file it opens.

**Comment by keithrbennett** [comment]
Something like this:

```ruby
  def process_file(object)
    
      line_num = 0
      zone = nil

      do_a_line = -> do
        begin

          ret = process_line(line)
          if (ret)
            rr = RR.create(ret)
            if (!zone)
              zone = []
            end
            zone.push(rr)
          end
        rescue Exception => e
          raise ParseException.new("Error reading line #{line_num} of #{file} : [#{line}]")
        end
      end

      if object.is_a?(StringIO)
        object.each_line { |line| do_a_line.(line) }
      else
        IO.foreach(object) { |line| do_a_line.(line) }
      end

      zone
    end
```

Actually, File instances support each_line too; it's only when a filespec (a String) is passed that we really need IO.foreach.

**Comment by tg90nor** [comment]
I believe this is all that is needed. StringIO and File objects can both use each_line, so if a filename is passed, just open a File, then use the same code.
```ruby
def process_file(filename)
  io = File.new(filename)
  zone = process_io(io, filename)
  return zone
end
```

**Comment by keithrbennett** [comment]
If I'm not mistaken, this would break existing code.  The current implementation works not only with filespecs, but with diverse kinds of IO objects, including not only File instances (open files) but also probably sockets and any other kind of custom object that might be passed that might work with IO.foreach.  So if someone is calling process_file with an IO other than a file (e.g. a socket), your code would attempt to call File.new on it.

In addition, unlike the current implementation, if a filespec is passed, I don't think your implementation would close the file after it's done, introducing a potentially serious open file leak. I added a test to the gist at https://gist.github.com/keithrbennett/8dc26274d5203bf5b45a (it's the last one) that seems to illustrate this.

**Comment by tg90nor** [comment]
Something like this should quite closely replicate the old behaviour then:

```ruby
def process_file(filename)
  if filename.is_a? IO
    zone = process_io(filename)
    filename.close
  else
    file = File.new(filename)
    zone = process_io(file)
    file.close
  end
  return zone
end
```

**Comment by keithrbennett** [comment]
The parameter name 'filename' is misleading and confusing.  I suggest we change it to something general enough to be reasonable for anything passed in...'source', for example.

This still potentially breaks existing calls because someone somewhere may be using a custom class that does not inherit from IO but has the required methods implemented (i.e. using duck typing rather than inheritance).  If you need to test on a class, then maybe testing it against String would be safer.

I suggest that if you implement this, you add tests illustrating that the following work: String (filespec), open file, StringIO, and a custom object containing the methods called by IO.foreach (maybe just each_line); and possibly also tests verifying that the number of open files does not increase (as in the gist I provided).

Also, I suggest using File.open instead of File.new, and if so, then the shorthand below which closes the file automatically can be used:

```ruby
def process_file(source)
  if source.is_a?(String)
    File.open(filespec) { |file| process_io(file) }
  else
    process_io(source)
  end
end
```

**Comment by tg90nor** [comment]
I incorporated your suggested changes to process_file, and also added tests for calling process_file with a File object, and calling process_io with a File or StringIO object.

**Comment by keithrbennett** [comment]
Do you disagree with what I said about the common practice of not leaving open files open and only closing files that we opened?

Also, Alex, do you have any thoughts about putting fixture files in the test directory rather than a fixtures directory?  Even better, I think, would be to include the text as a string in the test source code, and create a temporary file whose lifetime is just for the test (this is how I did it with my test code:

```ruby
 def setup ; File.write('delete.me', "delete\nme\n") end
def teardown ; File.delete('delete.me') end
```

...though for inclusion in the gem we should probably use Tempfile, something like this:
```ruby
 def setup
  @temp_file = Tempfile.new('foo')
  @temp_file << zone_file_text
  @temp_file.flush
end

def teardown
  @tempfile.delete
end

# get the filespec for your testing with @tempfile.path
```
 
Also, ...when comparing for equality, it's better to use assert_equal than assert, because if the two values are unequal, the error message is more descriptive.  Here I'm comparing 1 with 2, using assert_equal for the first and assert for the second:

```
  1) Failure:
OpenFileTest#test_2 [open_file_count_test.rb:50]:
Expected: 1
  Actual: 2


  2) Failure:
OpenFileTest#test_1 [open_file_count_test.rb:46]:
Failed assertion, no message given.
```

**Comment by tg90nor** [comment]
I close the file object passed to process_file to mimick the behaviour of IO.foreach, otherwise I believe my code only closes files it opens.

As for moving the dns zone fixture file into a fixture directory, or including it in the source, I have no problem with either. I'll include it in the source for now.

I will change my asserts into assert_equal.

**Comment by keithrbennett** [comment]
Thomas, thanks for making those changes.

The test 'test_illustrate_class_io_foreach_on_a_file_object_doesnt_close' in my gist shows that IO.foreach does _not_ close an open file passed to it.  It only closes something that it itself opens, that is, a file it opens when it is passed a filespec.

So the more concise version I provided, I think, will do exactly what we need it to do:

```ruby
def process_file(source)
  if source.is_a?(String)
    File.open(filespec) { |file| process_io(file) }
  else
    process_io(source)
  end
end
```

In my own code I'd make it even more concise, but you guys would probably consider that excessive. ;):

```ruby
def process_file(source)
  source.is_a?(String) \
    ? File.open(filespec) { |file| process_io(file) } \
    : process_io(source)
end
```

**Comment by tg90nor** [comment]
I have removed the source.close line in process_file. Now I don't close any objects I did not open.
Also, I have put the zone data into the test source code, and switched to using assert_equal.

**Comment by keithrbennett** [comment]
Nice, thank you.

My preference for the process_file method implementation would be the 3 or 4 line implementations I proposed instead of introducing the 'zone' variable and doubling the method's size, but I'll leave that to you and Alex.

One thing I just thought of that could be an additional improvement over the original version -- could you add the original exception's text in the ParseException's text?  Something like this?:

```ruby
 raise ParseException.new(
    "Error reading line #{io.lineno} of #{io.inspect}:\n    Line Text: [#{line}]\n    Nested error: #{e}")
```

Thanks.

**Comment by keithrbennett** [comment]
Thomas, you've made a lot of change at my request and I appreciate that.

Would you like the code to be committed as it is now?  Alex, I'm fine either way.

**Comment by tg90nor** [comment]
I think the code is ready.
There is a bug in the zone reader, that I chose not to address in this pull request (CNAME pointing to relative hostname will be converted to fqdn with two dots at the end. can be seen if you uncomment line 50 in test/tc_zone_reader.rb), so I will probably make another pull request soon to fix that bug.

**Comment by alexdalitz** [comment]
Thanks guys!

**Pull request merged**
