### PR TITLE
Fix compatibility with the `--enable-string-literal` Ruby option

### PR DESCRIPTION
**Pull request by casperisfine**
Ref: https://bugs.ruby-lang.org/issues/20205

This allow users to turn on frozen string literal if they so chose and make the gem compatible with future version sof Ruby for when frozen string literals may become the default.

### CODE REVIEW

**Comment by alexdalitz** [comment]
Interesting - thank you!
Sadly, the Ruby 3.3 tests had one failure - I'm not quite sure whether it's on your new "frozen" tests?

**Comment by casperisfine** [comment]
It failed on the worker that doesn't have string literals enabled. I think it's just a timeout or failed query that turned that way?

**Comment by casperisfine** [comment]
So I double checked, that test pass fine on my machine both with frozen string literal on and off.

I triggered a rebuild.

**Comment by casperisfine** [comment]
Actually, there seem to be an issue with some tests that consistently itmeout with string literals and don't without. I'll dig a bit more.

**Comment by casperisfine** [comment]
Alright, good call. I figured it out using `-d`. There was some `FrozenError` left, but it was happening in a background thread and the error was rescued.

Thanks to the debug flag I could see the errors printed even though they were rescued. It should go green now.

**Comment by alexdalitz** [comment]
OK, thanks very much for looking into and fixing the issue, and for your patch!
If it is a particular concern for you to have this in a release, please let me know - otherwise I'll probably wait until something else comes along...

**Review by alexdalitz — APPROVED** [review]

**Comment by casperisfine** [comment]
Not a huge concern, but running of a fork do raise some alarms. So no huge rush but depends what timeline you are thinking. If it's weeks it's fine :)

**Comment by casperisfine** [comment]
Oh and thanks for the quick merge ❤️

**Comment by alexdalitz** [comment]
Yeah no problem - I’m flat out with a commercial project right this minute, but I’ll try to get a new release out later today.

**Comment by alexdalitz** [comment]
Ok that’s v1.72.0 out - please let me know of any issues.

**Pull request merged**
