### PR TITLE
Refactor Resolv and its tests.

### PR DESCRIPTION
**Pull request by keithrbennett**
Simplify and clarify Resolv class and its tests.
Rename tc_dnsruby.rb to tc_resolv.rb.
Add pretty_backtrace as development dependency; it helps esp. with tests by displaying parameters to methods in stack trace.

### CODE REVIEW

**Comment by alexdalitz** [comment]
All seems fair enough, but two points -

a) -  require 'dnsruby/message'
+  require 'dnsruby/message/message'

b) jruby-head build is failing. Is that anything to do with these changes, or something to do with jruby-head?

Thanks,


Alex.

**Comment by keithrbennett** [comment]
Alex -

I apologize, I should have tested this with 1.9 and JRuby before issuing the pull request.  My bad.

I've modified the pretty_backtrace code to not load in JRuby and the tests are passing under JRuby now.

Regarding the require, message.rb is now in the dnsruby/message directory, so that's why we need the extra 'message' in the require spec.  I'm assuming that the intent was to require message.rb and not the entire message directory -- if that's not the case then we should not change it -- but I'm pretty sure that require is left over from before we created the message directory.

Thanks,
Keith

**Comment by keithrbennett** [comment]
Strange, there was an error a couple of runs ago (from https://travis-ci.org/keithrbennett/dnsruby/jobs/51292471):

```
 1) Failure:
TestRecur#test_recur [/home/travis/build/keithrbennett/dnsruby/test/tc_recur.rb:26]:
Failed assertion, no message given.
```

That's why I split out those 2 tests...but this run there was no error at all.

In any case, I'm fairly sure that had nothing to do with the code changes.  I think I'm doing pushing changes to this branch now. ;)

**Comment by alexdalitz** [comment]
Thanks for that!

One other question -

assert !!ret, "Query result was nil."

Why the double "!" ?

Thanks,


Alex.

**Comment by keithrbennett** [comment]
Alex -

Good catch.  It is redundant now and can be removed.  I originally had there something like:

```ruby
assert_equal true, !!ret, "Query result was nil."
```

!! can be used to convert a truthy value (anything other than nil or false) to true.  The first ! converts a truthy value to false, and the 2nd to true.  It's equivalent to:

```ruby
ret ? true : false
```

In the case where the value starts out as false, it will remain false after the !!.

Later I realized that assert would be more concise than assert_equal true... and changed it to that, but didn't think to look at the !!ret to see if that could be simplified.  It's no longer necessary, of course, because assert looks for truthiness (anything other than nil or false).  But by then I had made so many commits I didn't think you'd appreciate another one. ;)

Feel free to remove the '!!'.

Thanks,
Keith

**Comment by keithrbennett** [comment]
Wait, I just realized you didn't merge the pull request yet, so I removed the '!!' in another commit.

**Pull request merged**
