### PR TITLE
Fix create name include url special characters

### PR DESCRIPTION
**Pull request by mimuret**
```
["hoge/hoge","hoge#hoge","hoge?hoge"].each do |d|
  pp "input #{d}"
  pp "output #{Dnsruby::Name.create(d)}"
end
"input hoge/hoge"
"output hoge"
"input hoge#hoge"
"output hoge"
"input hoge?hoge"
"output hoge"
```

### CODE REVIEW

**Comment by keithrbennett** [comment]
@mimuret Thank you for this PR. I noticed that the gem you are using, `simpleidn` (https://github.com/mmriis/simpleidn) is not yet at version 1 and says it does not preserve case. @alexdalitz Is this a problem?

**Comment by alexdalitz** [comment]
Hi @mimuret -

Thanks for the patch!

I agree that your tests seem valid, and that the current IDN support in dnsruby seems to be failing here.

However, I'm a little concerned about the non-preservation of case. Although I accept that case does not matter in a pure DNS view, it is also the case that case preservation is a useful part of anti-spoofing defenses. In the ideal world, we would preserve the case that the client asked for.

Do you have any thoughts on this, please?

Thanks!


Alex.

**Comment by alexdalitz** [comment]
Ok, I guess this is a moot point, as Dnsruby downcases all labels anyway...

**Comment by mimuret** [comment]
RFC5890 describe,
> A-labels should be produced only in  lowercase

Already dnsruby can't save case-sensitive.

We choose case-sensitive or IDN support.

I like case-sensitive.

**Pull request merged**
